name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --file 01-compress-tgz/pom.xml clean package
      - run: mkdir staging && cp 01-compress-tgz/target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging